INSERT INTO genres (title)
VALUES ('Fantazy'),
	('Action'),
	('Drama'),
	('Western'),
	('Horror'),
	('Documentary'),
	('Thriller'),
	('Comedy'),
	('Adventure'),
	('Anime'),
	('Science fiction'),
	('Historic'),
	('Serial'),
	('Biopic'),
	('Melodrama'),
	('Music'),
	('Peplum'),
	('Crime film');