INSERT INTO nationalities (title, description)
VALUES ('USA', 'United States of America'),
	('GB', 'Great Britain'),
	('UA', 'Ukraine'),
	('DE', 'Deutschland'),
	('FR', 'France'),
	('AUS', 'Australia'),
	('BEL', 'Belgium'),
	('BRA', 'Brazil'),
	('GE', 'Georgia'),
	('DK', 'Denmark'),
	('IL', 'Israel'),
	('IN', 'India'),
	('IE', 'Ireland'),
	('IT', 'Italy'),
	('CA', 'Canada'),
	('CN', 'China'),
	('KR', 'Korea, Republic of'),
	('LV', 'Latvia'),
	('LT', 'Lithuania'),
	('NL', 'Netherlands'),
	('NO', 'Norway'),
	('PL', 'Poland'),
	('PT', 'Portugal'),
	('TR', 'Turkey'),
	('FI', 'Finland'),
	('CZ', 'Czech Republic'),
	('CH', 'Switzerland'),
	('EE', 'Estonia'),
	('JP', 'Japan'),
	('NZ', 'New Zealand'),
	('PUR', 'Puerto Rico'),
	('MLT', 'Malta'),
	('BEN', 'Benin'),
	('SWE', 'Sweden'),
	('FIN', 'Finland'),
	('RU', 'Russian'),
	('ISL', 'Iceland');